// Generated by scripts/add-team.py — edit freely (colors, logoPath, etc.).
const TEAM_CONFIG = {
  teamSlug: 'test-team',
  teamName: 'Test MS Team 01',
  shortName: 'Test MS Team 01',
  siteTitle: 'Test MS Team 01 Golf Tracker',

  // Optional — omit (or leave unset) to fall back to the shared golf-green-flag icon.
  // logoPath: '../../assets/branding/your-logo.png',
  // logoAlt: 'Test MS Team 01 logo',
  iconSpritePath: '../../assets/icons.svg',
  iconSymbolId: 'icon-golf-green',

  colors: {
    primary: '#d94f4f',
    secondary: '#3f8f3f',
    accent: '#e8801a',
    dark: '#1a1a1a',
  },

  github: {'owner': 'MSWD', 'repo': 'dempsey-golf-tracker', 'defaultBranch': 'main'},

  googleAuth: {
    clientId: '109861280365-iv2isv7funavdp8bllqhqjg5p2noq91v.apps.googleusercontent.com',
    deviceFlowWorkerUrl: 'https://middle-school-golf-tracker-auth.montgomery-software-and-web-development-account.workers.dev',
  },

  domain: 'https://middle-school-golf-tracker.mswd.us/teams/test-team',

  // Optional — highlights the top N ranked players on the rankings screen. Omit this field for
  // teams that don't want the highlight.
  rankHighlightCount: 3,

  // Optional — extra rankings columns (tryout avg, personal best, 9-hole HCP) plus red/yellow/
  // green shading on the rounds-played count. Omit this field (or set enabled: false) for teams
  // that don't want it.
  extendedRankingStats: {
    enabled: true,
    roundsThresholds: { yellow: 4, green: 6 }, // red below yellow, yellow up to (not incl.) green
  },
};
