#!/usr/bin/env python3
"""Scaffold a new team under src/teams/<slug>/ and add it to src/teams.json.

Run this locally, review what it prints, then `git add`/`commit`/`push` yourself — this script
never runs git for you. Stdlib only, no pip install needed.

Usage: scripts/add-team.py
"""
import json
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / "src"

# Shared across every team — keep this in sync with an existing team's team-config.js if these
# ever change (one Google OAuth Client + one Worker serve every team under this platform).
PLATFORM_GITHUB = {"owner": "MSWD", "repo": "dempsey-golf-tracker", "defaultBranch": "main"}
PLATFORM_GOOGLE_CLIENT_ID = "109861280365-iv2isv7funavdp8bllqhqjg5p2noq91v.apps.googleusercontent.com"
PLATFORM_WORKER_URL = "https://middle-school-golf-tracker-auth.montgomery-software-and-web-development-account.workers.dev"
PLATFORM_DOMAIN = "https://middle-school-golf-tracker.mswd.us"

INDEX_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Security-Policy"
        content="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self' {worker_url}; object-src 'none'; base-uri 'none'; frame-ancestors 'none'">
  <title>{site_title}</title>
  <link rel="icon" type="image/svg+xml" href="../../assets/favicon.svg">
  <link rel="stylesheet" href="../../css/styles.css">
  <script src="../../assets/vendor/chart.min.js"></script>
</head>
<body>

  <div id="icon-sprite"></div>

  <header class="app-header">
    <a href="../../index.html" class="back-link">&larr; All teams</a>
    <img class="logo" id="team-logo" alt="">
    <h1 id="team-title"></h1>
    <input type="text" id="season-name-input" class="admin-only" placeholder="Season name (e.g. 2026 Dempsey Golf Season)">
    <span id="season-name-display" class="viewer-only muted"></span>
    <div class="header-actions">
      <button id="btn-publish" class="admin-only">Publish report</button>
      <button id="btn-login">Login with Google</button>
    </div>
    <div id="login-status" class="muted full-width"></div>
  </header>

  <nav class="tabs">
    <button data-view="roster" class="active">Roster</button>
    <button data-view="courses">Courses</button>
    <button data-view="rounds">Rounds</button>
    <button data-view="rank">Rank</button>
    <button data-view="charts">Charts</button>
    <button data-view="matches">Matches</button>
    <button data-view="help">Help</button>
    <button data-view="maintenance" class="admin-only">Data Maintenance</button>
  </nav>

  <main>
    <section class="view active" id="view-roster"></section>
    <section class="view" id="view-courses"></section>
    <section class="view" id="view-rounds"></section>
    <section class="view" id="view-rank"></section>
    <section class="view" id="view-charts"></section>
    <section class="view" id="view-matches"></section>
    <section class="view" id="view-help"></section>
    <section class="view" id="view-maintenance"></section>
  </main>

  <footer id="app-footer" class="app-footer"></footer>

  <script src="team-config.js"></script>
  <script src="../../version.js"></script>
  <script src="../../js/html-utils.js"></script>
  <script src="../../js/models.js"></script>
  <script src="../../js/scoring-engine.js"></script>
  <script src="../../js/data-store.js"></script>
  <script src="../../js/ui-roster.js"></script>
  <script src="../../js/course-import.js"></script>
  <script src="../../js/ui-courses.js"></script>
  <script src="../../js/ui-rounds.js"></script>
  <script src="../../js/ui-charts.js"></script>
  <script src="../../js/ui-matches.js"></script>
  <script src="../../js/ui-help.js"></script>
  <script src="../../js/ui-maintenance.js"></script>
  <script src="../../js/google-auth.js"></script>
  <script src="../../js/github-publish.js"></script>
  <script src="../../js/app.js"></script>
</body>
</html>
"""

TEAM_CONFIG_TEMPLATE = """// Generated by scripts/add-team.py — edit freely (colors, logoPath, etc.).
const TEAM_CONFIG = {{
  teamSlug: '{slug}',
  teamName: '{name}',
  shortName: '{name}',
  siteTitle: '{site_title}',

  // Optional — omit (or leave unset) to fall back to the shared golf-green-flag icon.
  // logoPath: '../../assets/branding/your-logo.png',
  // logoAlt: '{name} logo',
  iconSpritePath: '../../assets/icons.svg',
  iconSymbolId: 'icon-golf-green',

  colors: {{
    primary: '#d94f4f',
    secondary: '#3f8f3f',
    accent: '#e8801a',
    dark: '#1a1a1a',
  }},

  github: {platform_github},

  googleAuth: {{
    clientId: '{client_id}',
    deviceFlowWorkerUrl: '{worker_url}',
  }},

  domain: '{domain}/teams/{slug}',
}};
"""

REPORTS_INDEX_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Security-Policy"
        content="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'">
  <title>{site_title} Reports</title>
  <link rel="icon" type="image/svg+xml" href="../../../assets/favicon.svg">
  <link rel="stylesheet" href="../../../css/styles.css">
</head>
<body>

  <header class="app-header">
    <a href="../../../index.html" class="back-link">&larr; All teams</a>
    <img class="logo" id="team-logo" alt="">
    <h1 id="team-title"></h1>
    <a class="btn" href="../index.html">Back to app</a>
  </header>

  <nav class="tabs">
    <button data-view="rank" class="active">Rankings</button>
    <button data-view="matches">Matches</button>
  </nav>

  <main>
    <section class="view active" id="view-report-rank">
      <div class="card">
        <div class="form-row">
          <label for="report-date-select">View as of:</label>
          <select id="report-date-select"></select>
        </div>
      </div>
      <div id="report-content"></div>
    </section>
    <section class="view" id="view-report-matches">
      <div id="report-matches-content"></div>
    </section>
  </main>

  <footer id="app-footer" class="app-footer"></footer>

  <script src="../team-config.js"></script>
  <script src="../../../version.js"></script>
  <script src="../../../js/html-utils.js"></script>
  <script src="../../../js/scoring-engine.js"></script>
  <script src="match-render.js"></script>
  <script src="report-viewer.js"></script>
</body>
</html>
"""

MATCH_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Security-Policy"
        content="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'">
  <title>{site_title} &mdash; Match Report</title>
  <link rel="icon" type="image/svg+xml" href="../../../assets/favicon.svg">
  <link rel="stylesheet" href="../../../css/styles.css">
</head>
<body>

  <header class="app-header">
    <a href="index.html" class="back-link">&larr; Full report</a>
    <img class="logo" id="team-logo" alt="">
    <h1 id="team-title"></h1>
  </header>

  <main>
    <div id="match-content"></div>
  </main>

  <footer id="app-footer" class="app-footer"></footer>

  <script src="../team-config.js"></script>
  <script src="../../../version.js"></script>
  <script src="../../../js/html-utils.js"></script>
  <script src="../../../js/scoring-engine.js"></script>
  <script src="match-render.js"></script>
  <script src="match-viewer.js"></script>
</body>
</html>
"""

EMPTY_SEED_DATA = {"players": [], "courses": [], "rounds": [], "matches": [], "tournaments": []}


def main():
    slug = input("Team slug (lowercase, hyphen-only, e.g. 'other-team'): ").strip().lower()
    if not slug or not all(c.isalnum() or c == "-" for c in slug):
        sys.exit("Slug must be lowercase letters/digits/hyphens only.")

    team_dir = SRC / "teams" / slug
    if team_dir.exists():
        sys.exit(f"src/teams/{slug} already exists — pick a different slug.")

    name = input("Display name (e.g. 'Riverside Middle School Golf'): ").strip()
    if not name:
        sys.exit("Display name is required.")

    # Matched case-insensitively by the Worker, against the caller's verified Google account email
    # (from a locally-verified ID token, not any Google directory/group lookup) — see
    # docs/auth-and-publishing.md's "teams.json — who can edit it" section. Unlike a GitHub handle,
    # an email doesn't become squattable if abandoned, but a deprovisioned/deleted Google Workspace
    # account is the rough equivalent gotcha: if an admin's school account gets deactivated,
    # teams.json must be updated to their new email in the same change, or they simply lose access
    # (fails safe, unlike the GitHub-handle-rename case).
    admins_raw = input("Admin Google account email(s), comma-separated: ").strip()
    admin_emails = [e.strip() for e in admins_raw.split(",") if e.strip()]
    if not admin_emails:
        sys.exit("At least one admin Google account email is required.")

    site_title = f"{name} Golf Tracker"

    team_dir.mkdir(parents=True)
    (team_dir / "index.html").write_text(INDEX_HTML_TEMPLATE.format(
        site_title=site_title,
        worker_url=PLATFORM_WORKER_URL,
    ))
    (team_dir / "team-config.js").write_text(TEAM_CONFIG_TEMPLATE.format(
        slug=slug,
        name=name,
        site_title=site_title,
        platform_github=json.dumps(PLATFORM_GITHUB).replace('"', "'"),
        client_id=PLATFORM_GOOGLE_CLIENT_ID,
        worker_url=PLATFORM_WORKER_URL,
        domain=PLATFORM_DOMAIN,
    ))
    (team_dir / "seed_data.json").write_text(json.dumps(EMPTY_SEED_DATA, indent=2) + "\n")

    reports_dir = team_dir / "reports" / "data"
    reports_dir.mkdir(parents=True)
    (team_dir / "reports" / "index.html").write_text(REPORTS_INDEX_HTML.format(site_title=site_title))
    (team_dir / "reports" / "match.html").write_text(MATCH_HTML.format(site_title=site_title))

    # report-viewer.js, match-render.js, and match-viewer.js carry no per-team data (everything
    # team-specific comes from team-config.js / fetched JSON at runtime), so every team's copy is
    # byte-identical to dempsey's canonical one — check-team-templates.py enforces that in CI.
    canonical_reports_dir = SRC / "teams" / "dempsey" / "reports"
    for shared_script in ("report-viewer.js", "match-render.js", "match-viewer.js"):
        src_file = canonical_reports_dir / shared_script
        if src_file.exists():
            (team_dir / "reports" / shared_script).write_text(src_file.read_text())
        else:
            print(f"Warning: could not find an existing {shared_script} to copy — add one manually.")

    teams_json_path = SRC / "teams.json"
    teams = json.loads(teams_json_path.read_text()) if teams_json_path.exists() else {}
    teams[slug] = {"name": name, "adminEmails": admin_emails}
    teams_json_path.write_text(json.dumps(teams, indent=2) + "\n")

    print(f"\nCreated src/teams/{slug}/ and added it to src/teams.json.")
    print("Review the new files, then commit and push yourself, e.g.:")
    print(f"  git add src/teams/{slug} src/teams.json")
    print(f'  git commit -m "Add {name} team"')
    print("  git push")


if __name__ == "__main__":
    main()
