#!/usr/bin/env python3
"""Scaffold a new team under src/teams/<slug>/ and add it to src/teams.json.

Run this locally, review what it prints, then `git add`/`commit`/`push` yourself — this script
never runs git for you. Stdlib only, no pip install needed.

Usage: scripts/add-team.py
"""
import json
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / "src"

# Shared across every team — keep this in sync with an existing team's team-config.js if these
# ever change (one GitHub App + one Worker serve every team under this platform).
PLATFORM_GITHUB = {"owner": "MSWD", "repo": "dempsey-golf-tracker", "defaultBranch": "main"}
PLATFORM_GITHUB_APP_CLIENT_ID = "Iv23lihwcQrIGaTeMaO4"
PLATFORM_WORKER_URL = "https://middle-school-golf-tracker-auth.montgomery-software-and-web-development-account.workers.dev"
PLATFORM_DOMAIN = "https://middle-school-golf-tracker.mswd.us"

INDEX_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{site_title}</title>
  <link rel="icon" type="image/svg+xml" href="../../assets/favicon.svg">
  <link rel="stylesheet" href="../../css/styles.css">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
</head>
<body>

  <div id="icon-sprite"></div>

  <header class="app-header">
    <img class="logo" id="team-logo" alt="">
    <h1 id="team-title"></h1>
    <div class="header-actions">
      <button id="btn-export">Export data</button>
      <button id="btn-import">Import data</button>
      <input type="file" id="file-import" accept="application/json" style="display:none">
      <button id="btn-publish" class="admin-only">Publish report</button>
      <button id="btn-login">Login with GitHub</button>
    </div>
    <div id="login-status" class="muted" style="width:100%"></div>
  </header>

  <nav class="tabs">
    <button data-view="roster" class="active">Roster</button>
    <button data-view="courses">Courses</button>
    <button data-view="rounds">Rounds</button>
    <button data-view="rank">Rank</button>
    <button data-view="charts">Charts</button>
    <button data-view="matches">Matches</button>
    <button data-view="help">Help</button>
  </nav>

  <main>
    <section class="view active" id="view-roster"></section>
    <section class="view" id="view-courses"></section>
    <section class="view" id="view-rounds"></section>
    <section class="view" id="view-rank"></section>
    <section class="view" id="view-charts"></section>
    <section class="view" id="view-matches"></section>
    <section class="view" id="view-help"></section>
  </main>

  <footer id="app-footer" class="app-footer"></footer>

  <script src="team-config.js"></script>
  <script src="../../version.js"></script>
  <script src="../../js/models.js"></script>
  <script src="../../js/scoring-engine.js"></script>
  <script src="../../js/data-store.js"></script>
  <script src="../../js/ui-roster.js"></script>
  <script src="../../js/ui-courses.js"></script>
  <script src="../../js/ui-rounds.js"></script>
  <script src="../../js/ui-charts.js"></script>
  <script src="../../js/ui-matches.js"></script>
  <script src="../../js/ui-help.js"></script>
  <script src="../../js/github-auth.js"></script>
  <script src="../../js/github-publish.js"></script>
  <script src="../../js/app.js"></script>
</body>
</html>
"""

TEAM_CONFIG_TEMPLATE = """// Generated by scripts/add-team.py — edit freely (colors, logoPath, etc.).
const TEAM_CONFIG = {{
  teamSlug: '{slug}',
  teamName: '{name}',
  shortName: '{name}',
  siteTitle: '{site_title}',

  // Optional — omit (or leave unset) to fall back to the shared golf-green-flag icon.
  // logoPath: '../../assets/branding/your-logo.png',
  // logoAlt: '{name} logo',
  iconSpritePath: '../../assets/icons.svg',
  iconSymbolId: 'icon-golf-green',

  colors: {{
    primary: '#d94f4f',
    secondary: '#3f8f3f',
    accent: '#e8801a',
    dark: '#1a1a1a',
  }},

  github: {platform_github},

  githubApp: {{
    clientId: '{client_id}',
    deviceFlowWorkerUrl: '{worker_url}',
  }},

  domain: '{domain}/teams/{slug}',
}};
"""

REPORTS_INDEX_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{site_title} Reports</title>
  <link rel="icon" type="image/svg+xml" href="../../../assets/favicon.svg">
  <link rel="stylesheet" href="../../../css/styles.css">
</head>
<body>

  <header class="app-header">
    <img class="logo" id="team-logo" alt="">
    <h1 id="team-title"></h1>
    <a class="btn" href="../index.html">Back to app</a>
  </header>

  <main>
    <div class="card">
      <div class="form-row">
        <label for="report-date-select">View as of:</label>
        <select id="report-date-select"></select>
      </div>
    </div>
    <div id="report-content"></div>
  </main>

  <footer id="app-footer" class="app-footer"></footer>

  <script src="../team-config.js"></script>
  <script src="../../../version.js"></script>
  <script src="../../../js/scoring-engine.js"></script>
  <script src="report-viewer.js"></script>
</body>
</html>
"""

EMPTY_SEED_DATA = {"players": [], "courses": [], "rounds": [], "matches": [], "tournaments": []}


def main():
    slug = input("Team slug (lowercase, hyphen-only, e.g. 'other-team'): ").strip().lower()
    if not slug or not all(c.isalnum() or c == "-" for c in slug):
        sys.exit("Slug must be lowercase letters/digits/hyphens only.")

    team_dir = SRC / "teams" / slug
    if team_dir.exists():
        sys.exit(f"src/teams/{slug} already exists — pick a different slug.")

    name = input("Display name (e.g. 'Riverside Middle School Golf'): ").strip()
    if not name:
        sys.exit("Display name is required.")

    admins_raw = input("Admin GitHub username(s), comma-separated: ").strip()
    admin_usernames = [u.strip() for u in admins_raw.split(",") if u.strip()]
    if not admin_usernames:
        sys.exit("At least one admin GitHub username is required.")

    site_title = f"{name} Golf Tracker"

    team_dir.mkdir(parents=True)
    (team_dir / "index.html").write_text(INDEX_HTML_TEMPLATE.format(site_title=site_title))
    (team_dir / "team-config.js").write_text(TEAM_CONFIG_TEMPLATE.format(
        slug=slug,
        name=name,
        site_title=site_title,
        platform_github=json.dumps(PLATFORM_GITHUB).replace('"', "'"),
        client_id=PLATFORM_GITHUB_APP_CLIENT_ID,
        worker_url=PLATFORM_WORKER_URL,
        domain=PLATFORM_DOMAIN,
    ))
    (team_dir / "seed_data.json").write_text(json.dumps(EMPTY_SEED_DATA, indent=2) + "\n")

    reports_dir = team_dir / "reports" / "data"
    reports_dir.mkdir(parents=True)
    (team_dir / "reports" / "index.html").write_text(REPORTS_INDEX_HTML.format(site_title=site_title))
    report_viewer_src = SRC / "teams" / "dempsey" / "reports" / "report-viewer.js"
    if report_viewer_src.exists():
        (team_dir / "reports" / "report-viewer.js").write_text(report_viewer_src.read_text())
    else:
        print("Warning: could not find an existing report-viewer.js to copy — add one manually.")

    teams_json_path = SRC / "teams.json"
    teams = json.loads(teams_json_path.read_text()) if teams_json_path.exists() else {}
    teams[slug] = {"name": name, "adminUsernames": admin_usernames}
    teams_json_path.write_text(json.dumps(teams, indent=2) + "\n")

    print(f"\nCreated src/teams/{slug}/ and added it to src/teams.json.")
    print("Review the new files, then commit and push yourself, e.g.:")
    print(f"  git add src/teams/{slug} src/teams.json")
    print(f'  git commit -m "Add {name} team"')
    print("  git push")


if __name__ == "__main__":
    main()
